### ISSUE TITLE
Incompatible Dependencies Have Missing Traits

### ISSUE THREAD

**Issue by palladionIT** [mikelodder7/vsss-rs#4]
I wanted to play around with the crate to implement DKG but I noticed that new versions dependencies seem to be incompatible. It seems that the `sha` dependency does not play nice with `curve25519_dalek` anymore. When I try to run the example `BLS12-381` code the compiler complains about missing trait bounds.

```
339 |         Self(EdwardsPoint::hash_from_bytes::<sha2::Sha512>(&seed))
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait 'curve25519_dalek::digest::FixedOutput' is not implemented for 'Sha512'
```

and 
```
339 |         Self(EdwardsPoint::hash_from_bytes::<sha2::Sha512>(&seed))
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `HashMarker` is not implemented for `Sha512`
```

I have not played around with it too much but I suspect pinning the dependencies to exact versions would work but of course would mean outdated dependencies. Is there a better solution to solve the issue? Are there any plans to add the missing traits?

Thanks a lot for the work in this crate I really appreciate it.

**Comment by mikelodder7** [comment]
Yeah the hash functions api is a breaking change from 0.9 to 0.10. If you use that it should work. I plan to make  an update to this in the next month or so

**Comment by mikelodder7** [comment]
Until then if you use 0.9 for the hash functions you should be fine

**Comment by delbonis** [comment]
Any updates on this?

**Comment by delbonis** [comment]
**Update, for anyone else that comes across this:** 

It was actually a bit tricky to notice why this was breaking but `cargo tree` helped a bit.  It turns out Cargo was using the pre.2 version of `curve25519-dalek`, which depends on `digest 0.10`, since it will upgrade from a pre.1 to a pre.2 on its own unless you specify it exactly.  So use the `=` prefix to make that explicit and it won't break anymore.  Downside if we're using a slightly older version of `digest` but I think that's okay.

My Cargo.toml looks like the below.  This is a little overkill but it does make sure we use exactly the versions we expect.

```toml
[dependencies]
curve25519-dalek = "=4.0.0-pre.1"

[dependencies.vsss-rs]
git = "https://github.com/mikelodder7/vsss-rs.git"
rev = "5d44175ddf8ed0437f0573759399c77bd56d2d79"
default-features = false
features = ["curve25519", "std"]
```

**Comment by mikelodder7** [comment]
Thanks for that. The update from `0.9` to `0.10` is proving to be more of a handful that I originally thought. Thanks for your patience.

**Comment by mikelodder7** [comment]
I believe I have addressed this. If so, I will close this
